<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Ejercicio1.aspx.cs" Inherits="TP6Grupo18.Ejercicio1.Ejercicio1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>Productos</h1>
            <br />
            <asp:GridView ID="gvProductos" runat="server"
            AllowPaging="True"
            PageSize="10"
            DataKeyNames="Id Producto"
            AutoGenerateColumns="True"
            AutoGenerateDeleteButton="True"
            OnRowDeleting="gvProductos_RowDeleting" />
        </div>
    </form>
</body>
</html>
